---
abstract: 'XS-only HTML Parsing'
author:
  - 'Jeffrey Kegler'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa-HTML-XS
provides:
  Marpa::HTML::XS:
    file: lib/Marpa/HTML/XS.pm
    version: 0.001_000
requires:
  Marpa::HTML: 0
  Marpa::XS: 1.002000
  perl: 5.01
resources:
  repository: git://github.com/jeffreykegler/Marpa--HTML--XS.git
version: 0.001_000
